"use client";
import {useState} from "react";

const demoMembers=[
 {id:"m-lin",name:"林悦",sex:"女",age:26,phone:"138 5276 1028",kind:"ordinary",followMode:"free",sample:"虚胖型",risk:3,measuredAt:"今天 10:18",metrics:{pbf:34.5,smm:19.2,bmi:20.8}},
 {id:"m-zhou",name:"周然",sex:"男",age:22,phone:"186 3041 7852",kind:"ordinary",followMode:"mine",sample:"匀称型",risk:1,measuredAt:"昨天 19:42",metrics:{pbf:17.7,smm:31.2,bmi:23.2}},
 {id:"m-xu",name:"许舟",sex:"男",age:30,phone:"139 7712 4639",kind:"ordinary",followMode:"other",sample:"矫健型",risk:1,measuredAt:"8月19日 17:25",metrics:{pbf:8.6,smm:31.6,bmi:21.8}},
 {id:"m-gu",name:"顾辰",sex:"男",age:29,phone:"177 9064 3315",kind:"private",sample:"强壮型",risk:2,measuredAt:"今天 08:45",target:"8周减脂 · 保持肌肉量",metrics:{pbf:16.9,smm:38.5,bmi:27}}
];
function Avatar({name}:{name:string}){return <span className="avatar">{name[0]}</span>}
function Task({m,label,note,onClick}:{m:any;label:string;note:string;onClick:()=>void}){return <button className={`task-card risk-${m.risk}`} onClick={onClick}><Avatar name={m.name}/><span className="task-copy"><b>{m.name}<em>{label}</em></b><small>{note}</small></span><span className="chevron">›</span></button>}
function Heading({title,side}:{title:string;side:React.ReactNode}){return <div className="section-heading"><h3>{title}</h3>{side}</div>}

export function WorkScreenV2({open,flash}:{open:(id:string)=>void;flash:(x:string)=>void}){const[completed,setCompleted]=useState(false),[riskOpen,setRiskOpen]=useState(false);return <div className="screen-content home-screen"><header className="home-header"><div><p>早上好，陈教练</p><h2>工作</h2><span>悦动健身 · 徐汇店</span></div></header><section className="work-summary"><div><strong>2</strong><span>我的待处理</span></div><div><strong>1</strong><span>普通会员待跟进</span></div></section>{completed?<><Heading title="已完成工作" side={<button className="text-button" onClick={()=>setCompleted(false)}>返回</button>}/>{[["林悦","已发送专业分析","今天 09:42"],["周然","已完成体测解读","昨天 19:52"],["顾辰","已完成复测评估","8月20日 16:30"]].map(x=><button className="task-card completed" key={x[0]} onClick={()=>flash(`${x[0]}：${x[1]}`)}><Avatar name={x[0]}/><span className="task-copy"><b>{x[0]}<em>已完成</em></b><small>{x[1]} · {x[2]}</small></span><span className="chevron">›</span></button>)}</>:<><Heading title="我的待处理" side={<span>2人</span>}/><Task m={demoMembers[1]} label="普通会员 · 我在跟进" note="AI 分析已生成｜下一步：审核并发送报告｜今天 18:00 前" onClick={()=>open("m-zhou")}/><Task m={demoMembers[3]} label="我的私教会员" note="已完成复测｜下一步：查看结果并调整训练安排｜明天 12:00 前" onClick={()=>open("m-gu")}/><Heading title="普通会员待跟进" side={<span>本门店教练均可处理</span>}/><Task m={demoMembers[0]} label="无人跟进 · 存在健康风险" note="刚完成体测｜下一步：查看报告并决定是否开始跟进" onClick={()=>setRiskOpen(true)}/><button className="completed-entry" onClick={()=>setCompleted(true)}>查看已完成工作 <span>12</span></button></>}{riskOpen&&<div className="risk-sheet"><div><h3>健康风险处理 · 林悦</h3><p>体脂率34.5%，骨骼肌量19.2kg。请先确认是否需要进一步沟通。</p><label><input type="checkbox"/> 我已向会员说明风险提示</label><label><input type="checkbox"/> 建议会员必要时咨询专业医疗人员</label><footer><button onClick={()=>setRiskOpen(false)}>稍后处理</button><button className="primary-action" onClick={()=>{setRiskOpen(false);flash("已记录风险沟通，并生成跟进任务")}}>记录并生成跟进任务</button></footer></div></div>}</div>}

export function MembersScreenV2({kind,setKind,open,overrides,converted}:{kind:"ordinary"|"private";setKind:(x:"ordinary"|"private")=>void;open:(id:string)=>void;overrides:Record<string,string>;converted:boolean}){const[query,setQuery]=useState(""),[filterOpen,setFilterOpen]=useState(false),[mode,setMode]=useState("all");const base=kind==="ordinary"?demoMembers.filter(x=>x.kind==="ordinary"&&!(converted&&x.id==="m-lin")):demoMembers.filter(x=>x.kind==="private");const list=base.filter(x=>`${x.name}${x.phone.slice(-4)}${x.id}`.toLowerCase().includes(query.toLowerCase())&&(kind==="private"||mode==="all"||(overrides[x.id]??x.followMode)===mode));return <div className="screen-content"><header className="page-header"><div><h2>会员</h2><p>悦动健身 · 徐汇店</p></div><div className="header-action"><button className="text-button" onClick={()=>setFilterOpen(!filterOpen)}>{filterOpen?"收起筛选":"筛选"}</button></div></header><div className="segmented"><button className={kind==="ordinary"?"active":""} onClick={()=>setKind("ordinary")}>普通会员 <span>{converted?2:3}</span></button><button className={kind==="private"?"active":""} onClick={()=>setKind("private")}>我的私教 <span>{converted?2:1}</span></button></div><label className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="搜索会员" placeholder="搜索姓名 / 手机号后四位 / 会员ID"/></label>{filterOpen&&kind==="ordinary"&&<div className="filter-strip">{[["all","全部"],["free","无人跟进"],["mine","我在跟进"],["other","他人跟进"]].map(x=><button key={x[0]} className={mode===x[0]?"active":""} onClick={()=>setMode(x[0])}>{x[1]}</button>)}</div>}<div className="list-note">同一时刻仅一名教练跟进；他人跟进时敏感信息脱敏</div><div className="member-list">{list.map(x=>{const fm=overrides[x.id]??x.followMode,state=fm==="mine"?"我在跟进":fm==="other"?"其他教练跟进中":"无人跟进";return <button className="member-row" key={x.id} onClick={()=>open(x.id)}><Avatar name={x.name}/><span className="member-copy"><b>{x.name}<small>{x.sex} · {x.age}岁 · {x.sample}</small></b><span>最近体测 {x.measuredAt}</span><span>体脂 {x.metrics.pbf}% · 骨骼肌 {x.metrics.smm}kg</span></span><span className="member-state">{kind==="ordinary"?<><em className={`follow-tag ${fm}`}>{state}</em>{x.risk>=3&&<i className="health-risk">存在健康风险</i>}</>:<i>{x.target}</i>}</span></button>})}{!list.length&&<div className="empty-state"><b>没有符合条件的会员</b><p>请调整搜索词或筛选条件。</p><button onClick={()=>{setQuery("");setMode("all")}}>清空条件</button></div>}</div></div>}

export function AnalysisV2({member,value,setValue,status,setStatus,back,follow,flash}:{member:any;value:string;setValue:(x:string)=>void;status:"draft"|"confirmed"|"sent";setStatus:(x:"draft"|"confirmed"|"sent")=>void;back:()=>void;follow:()=>void;flash:(x:string)=>void}){const[checked,setChecked]=useState(false),[error,setError]=useState("");const confirm=()=>{if(value.trim().length<20){setError("身体状态摘要至少填写20个字");return}if(!checked){setError("请先确认已核对会员数据与报告内容");return}setStatus("confirmed");setError("");flash("报告已确认，不需要主管审核")};return <div className="screen-content analysis-screen"><header className="page-header"><button className="back-button" onClick={back}>‹</button><div><h2>AI 专业分析</h2><p>{member.name} · 教练审核稿</p></div><div className="header-action"><span className="data-chip">{status==="sent"?"已发送":status==="confirmed"?"已确认":"待审核"}</span></div></header><div className="ai-process"><span className="done">数据校验</span><i/><span className="done">AI 生成</span><i/><span className={status!=="draft"?"done":"active"}>教练审核</span><i/><span className={status==="sent"?"done":""}>发送会员</span></div><section className="evidence-card"><b>结论依据</b><div><span>体脂率</span><strong>{member.metrics.pbf}%</strong><em>{member.metrics.pbf>28?"偏高":"正常"}</em></div><div><span>骨骼肌量</span><strong>{member.metrics.smm}kg</strong><em>{member.metrics.smm<20?"偏低":"正常"}</em></div><div><span>BMI</span><strong>{member.metrics.bmi}</strong><em>正常</em></div></section><label className="editor-label"><span>身体状态摘要 <i>*</i></span><textarea aria-invalid={!!error} value={value} onChange={e=>{setValue(e.target.value);setStatus("draft");setChecked(false);setError("")}}/>{error&&<em className="field-error">{error}</em>}</label><section className="priority-list"><b>优先改善建议</b>{[["1","每周 2—3 次力量训练"],["2","改善蛋白质摄入分配"],["3","4—6 周后复测"]].map(x=><div key={x[0]}><span>{x[0]}</span><p><strong>{x[1]}</strong><small>结合会员实际情况，由教练进一步确认</small></p></div>)}</section><div className="safety-note">本报告为AI草案，需教练核对，不用于疾病诊断或替代医疗意见。</div>{status==="draft"&&<label className="confirm-check"><input type="checkbox" checked={checked} onChange={e=>{setChecked(e.target.checked);setError("")}}/><span>我已核对会员数据与报告内容</span></label>}<div className="bottom-actions">{status==="draft"&&<button className="primary-action" onClick={confirm}>确认内容</button>}{status==="confirmed"&&<button className="primary-action" onClick={()=>{setStatus("sent");flash("报告已发送至会员承接端")}}>发送给会员</button>}{status==="sent"&&<button className="primary-action" onClick={follow}>记录跟进结果</button>}<button className="secondary-action" onClick={()=>flash("草稿已保存")}>保存草稿</button></div></div>}
