"use client";

import { useMemo, useState } from "react";
import "./polish.css";
import {WorkScreenV2,MembersScreenV2,AnalysisV2} from "./p0-components";

type FollowMode = "free" | "mine" | "other";
type Tab = "work" | "members" | "me";
type Screen = "root" | "detail" | "report" | "analysis" | "follow" | "convert" | "training" | "serviceData";
type MemberKind = "ordinary" | "private";
type Metrics = { weight:number;bmi:number;pbf:number;smm:number;muscle:number;bfm:number;vfi:number;bmr:number;tbw:number;whfr:number;bodyAge:number;score:number };
type Member = { id:string;name:string;sex:"男"|"女";age:number;phone:string;kind:MemberKind;followMode?:FollowMode;sample:string;risk:1|2|3|4;measuredAt:string;target?:string;metrics:Metrics };

const members: Member[] = [
  { id:"m-lin",name:"林悦",sex:"女",age:26,phone:"138 5276 1028",kind:"ordinary",followMode:"free",sample:"虚胖型",risk:3,measuredAt:"今天 10:18",metrics:{weight:55.3,bmi:20.8,pbf:34.5,smm:19.2,muscle:33.8,bfm:19.1,vfi:8,bmr:1153,tbw:26.3,whfr:.84,bodyAge:26.4,score:68}},
  { id:"m-zhou",name:"周然",sex:"男",age:22,phone:"186 3041 7852",kind:"ordinary",followMode:"mine",sample:"匀称型",risk:1,measuredAt:"昨天 19:42",metrics:{weight:70.2,bmi:23.2,pbf:17.7,smm:31.2,muscle:53.7,bfm:12.4,vfi:3,bmr:1618,tbw:41.8,whfr:.84,bodyAge:22.6,score:78}},
  { id:"m-xu",name:"许舟",sex:"男",age:30,phone:"139 7712 4639",kind:"ordinary",followMode:"other",sample:"矫健型",risk:1,measuredAt:"8月19日 17:25",metrics:{weight:62.3,bmi:21.8,pbf:8.6,smm:31.6,muscle:53.1,bfm:5.3,vfi:2,bmr:1600,tbw:41.3,whfr:.82,bodyAge:29.3,score:85}},
  { id:"m-gu",name:"顾辰",sex:"男",age:29,phone:"177 9064 3315",kind:"private",sample:"强壮型",risk:2,measuredAt:"今天 08:45",target:"8周减脂 · 保持肌肉量",metrics:{weight:84.7,bmi:27,pbf:16.9,smm:38.5,muscle:65.7,bfm:14.3,vfi:2,bmr:1890,tbw:51.1,whfr:.83,bodyAge:29.1,score:87}},
];
const previous:Record<string,Partial<Metrics>>={"m-lin":{weight:54.8,pbf:32.9,smm:19.6,bfm:18,vfi:7},"m-zhou":{weight:69.4,pbf:18.2,smm:30.8,bfm:12.6,vfi:3},"m-xu":{weight:61.9,pbf:9.1,smm:31.2,bfm:5.6,vfi:2},"m-gu":{weight:86.1,pbf:18.4,smm:38.2,bfm:15.8,vfi:3}};
const tabs:{id:Tab;label:string;symbol:string}[]=[{id:"work",label:"工作",symbol:"⌂"},{id:"members",label:"会员",symbol:"◎"},{id:"me",label:"我的",symbol:"○"}];
const hasHealthRisk=(level:number)=>level>=3;
const riskText=(level:number)=>hasHealthRisk(level)?"存在健康风险":"";
const delta=(a:number,b?:number)=>b===undefined?"—":`${a-b>0?"+":""}${(a-b).toFixed(1)}`;

export default function Home(){
  const[tab,setTab]=useState<Tab>("work");const[screen,setScreen]=useState<Screen>("root");const[memberTab,setMemberTab]=useState<MemberKind>("ordinary");const[selectedId,setSelectedId]=useState("m-lin");const[overrides,setOverrides]=useState<Record<string,FollowMode>>({});const[analysisStatus,setAnalysisStatus]=useState<"draft"|"confirmed"|"sent">("draft");const[planStatus,setPlanStatus]=useState<"draft"|"sent">("draft");const[converted,setConverted]=useState(false);const[toast,setToast]=useState("");const[analysisText,setAnalysisText]=useState("本次体重处于正常范围，但体脂率偏高、骨骼肌量偏低，呈现体重正常但身体组成需要改善的特点。建议先以提升力量训练频次和蛋白质摄入质量为核心，不宜单纯追求快速减重。");
  const base=members.find(x=>x.id===selectedId)??members[0];const member=useMemo(()=>selectedId==="m-lin"&&converted?{...base,kind:"private" as const,followMode:undefined,target:"12周增肌减脂"}:{...base,followMode:overrides[selectedId]??base.followMode},[base,converted,overrides,selectedId]);
  const flash=(msg:string)=>{setToast(msg);window.setTimeout(()=>setToast(""),2200)};const openMember=(id:string)=>{setSelectedId(id);setScreen("detail")};const goRoot=(next?:Tab)=>{if(next)setTab(next);setScreen("root")};
  return <main className="prototype-stage">
    <section className="phone-shell"><div className="status-bar"><span>9:41</span><span>● ● ▰</span></div><div className="app-viewport">
      {screen==="root"&&tab==="work"&&<WorkScreenV2 open={openMember} flash={flash}/>} 
      {screen==="root"&&tab==="members"&&<MembersScreenV2 kind={memberTab} setKind={setMemberTab} open={openMember} overrides={overrides} converted={converted}/>} 
      {screen==="root"&&tab==="me"&&<MeScreen serviceData={()=>setScreen("serviceData")}/>} 
      {screen==="serviceData"&&<ServiceData back={()=>setScreen("root")} open={openMember}/>} 
      {screen==="detail"&&<MemberDetail member={member} back={()=>goRoot("members")} report={()=>setScreen("report")} analysis={()=>setScreen("analysis")} follow={()=>setScreen("follow")} convert={()=>setScreen("convert")} training={()=>setScreen("training")} start={()=>{setOverrides(s=>({...s,[member.id]:"mine"}));flash("已取得跟进权，其他教练将看到脱敏状态")}} flash={flash}/>} 
      {screen==="report"&&<Report member={member} back={()=>setScreen("detail")} analysis={()=>setScreen("analysis")}/>} 
      {screen==="analysis"&&<AnalysisV2 member={member} value={analysisText} setValue={setAnalysisText} status={analysisStatus} setStatus={setAnalysisStatus} back={()=>setScreen("detail")} follow={()=>setScreen("follow")} flash={flash}/>} 
      {screen==="follow"&&<Follow member={member} back={()=>setScreen("detail")} convert={()=>setScreen("convert")} flash={flash}/>} 
      {screen==="convert"&&<Convert member={member} back={()=>setScreen("detail")} confirm={()=>{setConverted(true);setScreen("training");flash("已建立唯一私教归属")}}/>} 
      {screen==="training"&&<Training member={member} status={planStatus} setStatus={setPlanStatus} back={()=>setScreen("detail")} flash={flash}/>} 
    </div>{screen==="root"&&<nav className="bottom-nav">{tabs.map(x=><button key={x.id} onClick={()=>goRoot(x.id)} className={tab===x.id?"active":""}><span>{x.symbol}</span>{x.label}</button>)}</nav>}{toast&&<div className="toast">{toast}</div>}</section>
  </main>;
}

function PageHeader({title,subtitle,back,action}:{title:string;subtitle?:string;back?:()=>void;action?:React.ReactNode}){return <header className="page-header">{back&&<button className="back-button" onClick={back}>‹</button>}<div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action&&<div className="header-action">{action}</div>}</header>}
function WorkScreen({open}:{open:(id:string)=>void}){return <div className="screen-content home-screen"><header className="home-header"><div><p>早上好，陈教练</p><h2>工作</h2><span>悦动健身 · 徐汇店</span></div></header><section className="work-summary"><div><strong>2</strong><span>我的待处理</span></div><div><strong>1</strong><span>普通会员待跟进</span></div></section><Heading title="我的待处理" action={<span>2人</span>}/><Task member={members[1]} label="普通会员 · 我在跟进" note="AI 分析已生成｜下一步：审核并发送报告｜今天 18:00 前" click={()=>open("m-zhou")}/><Task member={members[3]} label="我的私教会员" note="已完成复测｜下一步：查看结果并调整训练安排｜明天 12:00 前" click={()=>open("m-gu")}/><Heading title="普通会员待跟进" action={<span>本门店教练均可处理</span>}/><Task member={members[0]} label="无人跟进 · 存在健康风险" note="刚完成体测｜下一步：查看报告并决定是否开始跟进" click={()=>open("m-lin")}/><button className="completed-entry">查看已完成工作 <span>12</span></button></div>}
function Heading({title,action}:{title:string;action:React.ReactNode}){return <div className="section-heading"><h3>{title}</h3>{action}</div>}
function Task({member,label,note,click}:{member:Member;label:string;note:string;click:()=>void}){return <button className={`task-card risk-${member.risk}`} onClick={click}><span className="avatar">{member.name[0]}</span><span className="task-copy"><b>{member.name}<em>{label}</em></b><small>{note}</small></span><span className="chevron">›</span></button>}

function MembersScreen({kind,setKind,open,overrides,converted}:{kind:MemberKind;setKind:(x:MemberKind)=>void;open:(id:string)=>void;overrides:Record<string,FollowMode>;converted:boolean}){const list=kind==="ordinary"?members.filter(x=>x.kind==="ordinary"&&!(converted&&x.id==="m-lin")):[...members.filter(x=>x.kind==="private"),...(converted?[{...members[0],kind:"private" as const,target:"12周增肌减脂"}]:[])];return <div className="screen-content"><PageHeader title="会员" subtitle="悦动健身 · 徐汇店" action={<button className="text-button">筛选</button>}/><div className="segmented"><button className={kind==="ordinary"?"active":""} onClick={()=>setKind("ordinary")}>普通会员 <span>{converted?2:3}</span></button><button className={kind==="private"?"active":""} onClick={()=>setKind("private")}>我的私教 <span>{converted?2:1}</span></button></div><label className="search-box"><span>⌕</span><input aria-label="搜索会员" placeholder="搜索姓名 / 手机号后四位"/></label>{kind==="ordinary"&&<div className="list-note">状态表示该会员相对于当前教练的跟进归属；同一时刻仅一名教练跟进</div>}<div className="member-list">{list.map(x=>{const mode=overrides[x.id]??x.followMode;const state=mode==="mine"?"我在跟进":mode==="other"?"其他教练跟进中":"无人跟进";return <button className="member-row" key={x.id} onClick={()=>open(x.id)}><span className="avatar">{x.name[0]}</span><span className="member-copy"><b>{x.name}<small>{x.sex} · {x.age}岁 · {x.sample}</small></b><span>最近体测 {x.measuredAt}</span><span>体脂 {x.metrics.pbf}% · 骨骼肌 {x.metrics.smm}kg</span></span><span className="member-state">{kind==="ordinary"?<><em className={`follow-tag ${mode}`}>{state}</em>{hasHealthRisk(x.risk)&&<i className="health-risk">存在健康风险</i>}</>:<i>{x.target}</i>}</span></button>})}</div></div>}

function MemberDetail({member,back,report,analysis,follow,convert,training,start,flash}:{member:Member;back:()=>void;report:()=>void;analysis:()=>void;follow:()=>void;convert:()=>void;training:()=>void;start:()=>void;flash:(x:string)=>void}){const other=member.kind==="ordinary"&&member.followMode==="other",mine=member.kind==="ordinary"&&member.followMode==="mine",free=member.kind==="ordinary"&&member.followMode==="free";return <div className="screen-content detail-screen"><PageHeader title={member.name} subtitle={`${member.sex} · ${member.age}岁 · ${member.sample}`} back={back} action={<span className={`risk-tag risk-${member.risk}`}>{riskText(member.risk)}</span>}/>{other&&<Banner kind="locked" title="该会员正在被其他教练跟进" text="你仍可查看完整体测报告；手机号、跟进人和具体备注已隐藏。"/>}{mine&&<Banner kind="mine" title="当前跟进权属于你" text="请在 48 小时内完成联系、专业分析或更新跟进结果。"/>}{free&&<Banner title="当前无人跟进" text="开始跟进后将暂时锁定该会员，避免重复联系。"/>}{member.kind==="private"&&<Banner kind="private" title="我的私教会员" text={member.target??"尚未设置训练目标"}/>}<section className="contact-card"><div><span>手机号</span><b>{other?"138 **** 1028":member.phone}</b></div><button disabled={other} onClick={()=>flash("已记录本次电话联系操作")}>{other?"不可联系":"拨打电话"}</button></section><section className="score-card"><div className="score-ring"><strong>{member.metrics.score}</strong><span>身体评分</span></div><div><span>最新体测 · {member.measuredAt}</span><b>{member.sample}</b><p>体脂 {member.metrics.pbf}% · 骨骼肌 {member.metrics.smm}kg</p></div></section><section className="metric-preview"><Metric label="体重" value={`${member.metrics.weight} kg`}/><Metric label="BMI" value={String(member.metrics.bmi)}/><Metric label="体脂率" value={`${member.metrics.pbf}%`} tone={member.metrics.pbf>28?"warn":""}/><Metric label="骨骼肌" value={`${member.metrics.smm} kg`} tone={member.metrics.smm<20?"warn":""}/></section><button className="full-row" onClick={report}><span><b>完整体测报告</b><small>体成分、历史趋势、数据质量</small></span><i>›</i></button>{member.kind==="ordinary"&&<section className="action-panel">{free&&<button className="primary-action" onClick={start}>开始跟进</button>}{mine&&<><button className="primary-action" onClick={analysis}>生成 / 查看 AI 专业分析</button><div className="dual-actions"><button onClick={follow}>记录跟进结果</button><button onClick={convert}>转为私教会员</button></div></>}{other&&<><button className="disabled-action" disabled>AI 专业分析不可用</button><p className="permission-help">其他教练跟进期间，不可联系、生成报告、发送报告或转私教。</p></>}<p className="scope-note">普通会员不能生成训练方案</p></section>}{member.kind==="private"&&<section className="action-panel"><button className="primary-action" onClick={analysis}>审核 AI 专业分析</button><button className="secondary-action" onClick={training}>查看 / 调整训练方案</button></section>}</div>}
function Banner({kind="",title,text}:{kind?:string;title:string;text:string}){return <div className={`permission-banner ${kind}`}><b>{title}</b><p>{text}</p></div>}
function Metric({label,value,tone=""}:{label:string;value:string;tone?:string}){return <div className={tone}><span>{label}</span><b>{value}</b></div>}

function Report({member,back,analysis}:{member:Member;back:()=>void;analysis:()=>void}){const old=previous[member.id]??{};const rows:[[string,number,number|undefined,string]]|[string,number,number|undefined,string][]=[["体重",member.metrics.weight,old.weight,"kg"],["体脂率",member.metrics.pbf,old.pbf,"%"],["骨骼肌量",member.metrics.smm,old.smm,"kg"],["体脂肪量",member.metrics.bfm,old.bfm,"kg"],["内脏脂肪等级",member.metrics.vfi,old.vfi,"级"]];return <div className="screen-content report-screen"><PageHeader title="完整体测报告" subtitle={`${member.name} · ${member.measuredAt}`} back={back} action={<span className="data-chip">数据有效</span>}/><section className="report-hero"><div className="score-ring"><strong>{member.metrics.score}</strong><span>身体评分</span></div><div><b>{member.sample}</b><p>体重正常不代表身体组成理想，请结合肌肉量和体脂率综合判断。</p></div></section><section className="report-section"><Heading title="核心指标" action={<span>附件样例数据</span>}/><div className="report-metrics"><Metric label="BMI" value={String(member.metrics.bmi)}/><Metric label="体脂率" value={`${member.metrics.pbf}%`} tone={member.metrics.pbf>28?"warn":""}/><Metric label="骨骼肌量" value={`${member.metrics.smm}kg`} tone={member.metrics.smm<20?"warn":""}/><Metric label="基础代谢" value={`${member.metrics.bmr}kcal`}/><Metric label="体水分" value={`${member.metrics.tbw}kg`}/><Metric label="腰高比" value={String(member.metrics.whfr)}/></div></section><section className="report-section"><Heading title="两次体测对比" action={<span>历史值为演示模拟</span>}/><div className="comparison-table"><div className="comparison-head"><span>指标</span><span>上次</span><span>本次</span><span>变化</span></div>{rows.map(([label,current,prev,unit])=><div key={label}><b>{label}</b><span>{prev??"—"}{prev!==undefined?unit:""}</span><span>{current}{unit}</span><em>{delta(current,prev)}</em></div>)}</div></section><section className="report-section"><Heading title="AI 基础解读" action={<span>无需教练审核</span>}/><div className="ai-summary"><b>核心发现</b><p>{member.metrics.pbf>28?"体脂率偏高，同时骨骼肌量偏低，应优先改善身体组成，而非只关注体重。":"当前身体组成整体较平衡，可结合个人目标关注肌肉与体脂的长期趋势。"}</p><small>基础解读仅用于健康管理参考，不构成医疗诊断。</small></div></section><button className="sticky-action" onClick={analysis}>生成教练专业分析</button></div>}

function Analysis({member,value,setValue,status,setStatus,back,follow,flash}:{member:Member;value:string;setValue:(x:string)=>void;status:"draft"|"confirmed"|"sent";setStatus:(x:"draft"|"confirmed"|"sent")=>void;back:()=>void;follow:()=>void;flash:(x:string)=>void}){return <div className="screen-content analysis-screen"><PageHeader title="AI 专业分析" subtitle={`${member.name} · 教练审核稿`} back={back} action={<span className="data-chip">{status==="sent"?"已发送":status==="confirmed"?"已确认":"待审核"}</span>}/><div className="ai-process"><span className="done">数据校验</span><i></i><span className="done">AI 生成</span><i></i><span className={status!=="draft"?"done":"active"}>教练审核</span><i></i><span className={status==="sent"?"done":""}>发送会员</span></div><section className="evidence-card"><b>结论依据</b><div><span>体脂率</span><strong>{member.metrics.pbf}%</strong><em>{member.metrics.pbf>28?"偏高":"正常"}</em></div><div><span>骨骼肌量</span><strong>{member.metrics.smm}kg</strong><em>{member.metrics.smm<20?"偏低":"正常"}</em></div><div><span>BMI</span><strong>{member.metrics.bmi}</strong><em>正常</em></div></section><label className="editor-label"><span>身体状态摘要</span><textarea value={value} onChange={e=>{setValue(e.target.value);setStatus("draft")}}/></label><section className="priority-list"><b>优先改善建议</b>{[["1","每周 2—3 次力量训练","从全身基础动作开始，逐步增加负荷"],["2","改善蛋白质摄入分配","结合个人饮食习惯，由教练进一步沟通"],["3","4—6 周后复测","以体脂率和骨骼肌量趋势评估效果"]].map(x=><div key={x[0]}><span>{x[0]}</span><p><strong>{x[1]}</strong><small>{x[2]}</small></p></div>)}</section><div className="safety-note">本报告为 AI 草案。教练需核对数据和内容，不用于疾病诊断或替代医疗意见。</div><div className="bottom-actions">{status==="draft"&&<button className="primary-action" onClick={()=>{setStatus("confirmed");flash("报告已确认，不需要主管审核")}}>确认内容</button>}{status==="confirmed"&&<button className="primary-action" onClick={()=>{setStatus("sent");flash("报告已发送至会员承接端")}}>发送给会员</button>}{status==="sent"&&<button className="primary-action" onClick={follow}>记录跟进结果</button>}<button className="secondary-action" onClick={()=>flash("草稿已保存")}>保存草稿</button></div></div>}

function Follow({member,back,convert,flash}:{member:Member;back:()=>void;convert:()=>void;flash:(x:string)=>void}){const[result,setResult]=useState("待转私教");return <div className="screen-content form-screen"><PageHeader title="记录跟进结果" subtitle={`${member.name} · 当前跟进权属于你`} back={back}/><label><span>跟进方式</span><select defaultValue="电话"><option>电话</option><option>当面</option><option>其他</option></select></label><label><span>跟进结果</span><select value={result} onChange={e=>setResult(e.target.value)}><option>已完成体测解读</option><option>待转私教</option><option>继续跟进</option><option>暂不跟进</option></select></label><label><span>跟进备注</span><textarea defaultValue="已电话讲解体脂率和骨骼肌量问题。会员希望通过力量训练改善体型，对私教体验课有兴趣。"/></label><label><span>下一次跟进时间</span><input defaultValue="2026-08-23 18:00"/></label><div className="visibility-note"><b>可见范围</b><p>其他教练在当前跟进期间不可查看具体备注。</p></div><button className="primary-action wide" onClick={()=>{flash(`已保存：${result}`);result==="待转私教"?convert():back()}}>保存结果</button></div>}
function Convert({member,back,confirm}:{member:Member;back:()=>void;confirm:()=>void}){return <div className="screen-content convert-screen"><PageHeader title="转为私教会员" subtitle="MVP 手动建立唯一归属" back={back}/><div className="confirm-visual"><span className="avatar big">{member.name[0]}</span><h3>{member.name}</h3><p>普通会员 → 陈教练的私教会员</p></div><section className="confirm-list"><div><span>当前服务门店</span><b>悦动健身 · 徐汇店</b></div><div><span>所属教练</span><b>陈教练（当前账号）</b></div><div><span>建立日期</span><b>2026-08-21</b></div><div><span>历史数据</span><b>体测、报告、跟进记录全部保留</b></div></section><div className="safety-note"><b>请确认会员已正式购买私教服务。</b><br/>正式产品将优先通过场馆 SaaS 的订单或卡项自动同步。</div><button className="primary-action wide" onClick={confirm}>确认建立私教关系</button></div>}

function Training({member,status,setStatus,back,flash}:{member:Member;status:"draft"|"sent";setStatus:(x:"draft"|"sent")=>void;back:()=>void;flash:(x:string)=>void}){return <div className="screen-content training-screen"><PageHeader title="训练方案" subtitle={`${member.name} · AI 草案 / 教练确认`} back={back} action={<span className="data-chip">{status==="sent"?"已下发":"草稿"}</span>}/><section className="training-brief"><div><span>目标</span><b>{member.target??"12周增肌减脂"}</b></div><div><span>频次</span><b>每周 3 次 · 每次 60 分钟</b></div><div><span>条件</span><b>健身房器械 · 无当前疼痛</b></div></section><div className="safety-pass">✓ 安全校验通过 · 当前无阻断项</div><section className="week-card"><header><b>第 1—4 周 · 基础适应</b><span>3 次 / 周</span></header><Workout title="训练 A · 下肢与核心" items={["高脚杯深蹲 · 3×10","罗马尼亚硬拉 · 3×10","平板支撑 · 3×30秒"]}/><Workout title="训练 B · 上肢推拉" items={["坐姿划船 · 3×12","器械推胸 · 3×10","面拉 · 3×15"]}/><Workout title="训练 C · 全身循环" items={["腿举 · 3×12","高位下拉 · 3×12","低强度有氧 · 20分钟"]}/></section><section className="plan-note"><b>教练说明</b><textarea defaultValue="前两周重点熟悉动作和稳定节奏，RPE 控制在 6—7。若出现疼痛或异常不适，立即停止并重新评估。"/></section><div className="bottom-actions">{status==="draft"?<button className="primary-action" onClick={()=>{setStatus("sent");flash("训练方案 V1 已下发")}}>确认并下发</button>:<button className="primary-action" onClick={()=>flash("会员端预览已打开")}>查看会员端效果</button>}<button className="secondary-action" onClick={()=>flash("方案草稿已保存")}>保存草稿</button></div></div>}
function Workout({title,items}:{title:string;items:string[]}){return <details open><summary>{title}<span>编辑</span></summary>{items.map(x=><div className="exercise" key={x}><i>↕</i><span>{x}</span><button>替换</button></div>)}</details>}

function MeScreen({serviceData}:{serviceData:()=>void}){return <div className="screen-content me-screen"><PageHeader title="我的" subtitle="账号、权限与服务数据"/><section className="profile-card"><span className="avatar big">陈</span><div><h3>陈教练</h3><p>悦动健身 · 徐汇店</p><span>教练 · 在职</span></div></section><button className="service-entry" onClick={serviceData}><span><b>我的服务数据</b><small>2026年8月 · 当前门店 · 我的数据</small></span><strong>本月服务 18 人</strong><em>完成体测解读 15 份 · 发送报告 13 份</em><i>›</i></button><div className="settings-list"><button><span>AI 能力与权限</span><em>专业分析、训练方案</em><i>›</i></button><button><span>隐私与安全</span><i>›</i></button><button><span>帮助与反馈</span><i>›</i></button></div></div>}
function ServiceData({back,open}:{back:()=>void;open:(id:string)=>void}){return <div className="screen-content service-screen"><PageHeader title="我的服务数据" subtitle="2026年8月" back={back}/><div className="data-scope"><b>当前门店 · 我的数据</b><span>数据更新至 8月21日 10:30</span></div><section className="service-overview"><h3>本月服务总览</h3><div><b>18<small>人</small></b><span>服务会员</span></div><div><b>15<small>份</small></b><span>完成体测解读</span></div><div><b>13<small>份</small></b><span>发送分析报告</span></div></section><section className="data-section"><h3>服务会员构成</h3><div className="composition-row"><span>普通会员服务<small>跟进、解读或发送报告</small></span><b>10人</b></div><div className="composition-bar"><i style={{width:"56%"}}></i></div><div className="composition-row"><span>我的私教会员<small>复测、解读或训练服务</small></span><b>8人</b></div><div className="composition-bar private"><i style={{width:"44%"}}></i></div></section><section className="data-section"><h3>普通会员跟进结果</h3><div className="mini-stats"><div><b>10人</b><span>本月跟进</span></div><div><b>8人</b><span>完成体测解读</span></div><div><b>2人</b><span>转为私教</span></div></div></section><section className="data-section"><h3>我的私教服务</h3><div className="service-lines"><p><span>当前私教会员</span><b>12人</b></p><p><span>本月完成复测</span><b>6人</b></p><p><span>完成体测解读</span><b>6份</b></p><p><span>发送专业分析</span><b>5份</b></p></div></section><section className="data-section service-records"><Heading title="本月服务记录" action={<span>查看全部</span>}/><button onClick={()=>open("m-lin")}><time>8月20日</time><span><b>林悦 · 普通会员</b><small>发送专业分析报告</small></span><i>›</i></button><button onClick={()=>open("m-zhou")}><time>8月19日</time><span><b>周然 · 普通会员</b><small>完成体测解读</small></span><i>›</i></button><button onClick={()=>open("m-gu")}><time>8月18日</time><span><b>顾辰 · 私教会员</b><small>完成复测</small></span><i>›</i></button></section></div>}
